### ISSUE TITLE
Delete VM action failed with PriorRequestNotCompleteException on AWS

### ISSUE THREAD

**Issue by vshipb** [AltisourceLabs/ecloudmanager#4]
17:11:07,626 INFO  [stdout](pool-11-thread-7) 17:11:07,621 ERROR [org.ecloudmanager.service.execution.SingleAction](pool-11-thread-7) Failed to execute action Delete VM[petclinic-web]: 
17:11:07,626 INFO  [stdout](pool-11-thread-7)  com.amazonaws.services.route53.model.PriorRequestNotCompleteException: The request was rejected because Route 53 was still processing a prior request. (Service: AmazonRoute53; Status Code: 400; Error Code: PriorRequestNotComplete; Request ID: 967846ce-f813-11e5-bee1-519728f467d4)
17:11:07,626 INFO  [stdout](pool-11-thread-7)  at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1383) ~[aws-java-sdk-core-1.10.61.jar:?]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902) ~[aws-java-sdk-core-1.10.61.jar:?]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607) ~[aws-java-sdk-core-1.10.61.jar:?]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376) ~[aws-java-sdk-core-1.10.61.jar:?]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338) ~[aws-java-sdk-core-1.10.61.jar:?]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287) ~[aws-java-sdk-core-1.10.61.jar:?]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at com.amazonaws.services.route53.AmazonRoute53Client.invoke(AmazonRoute53Client.java:3689) ~[aws-java-sdk-route53-1.10.61.jar:?]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at com.amazonaws.services.route53.AmazonRoute53Client.changeResourceRecordSets(AmazonRoute53Client.java:468) ~[aws-java-sdk-route53-1.10.61.jar:?]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at org.ecloudmanager.service.aws.AWSVmService.deleteDnsRecord(AWSVmService.java:189) ~[classes:?]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at org.ecloudmanager.service.aws.AWSVmService.deleteVm(AWSVmService.java:227) ~[classes:?]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at org.ecloudmanager.actions.AWSVmActions.lambda$getDeleteVmAction$1(AWSVmActions.java:86) ~[classes:?]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at org.ecloudmanager.actions.AWSVmActions$$Lambda$132/1016623523.run(Unknown Source) ~[?:?]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at org.ecloudmanager.service.execution.SingleAction.run(SingleAction.java:100) [classes:?]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_31]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_31]
17:11:07,627 INFO  [stdout](pool-11-thread-7)  at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]

**Comment by vshipb** [comment]
And  after that, when deploying application:
17:16:37,646 INFO  [stdout](pool-15-thread-5) 17:16:37,644 ERROR [org.ecloudmanager.service.execution.SingleAction](pool-15-thread-5) Failed to execute action Create and start VM[petclinic-web]: 
17:16:37,646 INFO  [stdout](pool-15-thread-5)  com.amazonaws.services.route53.model.InvalidChangeBatchException: Tried to create resource record set [name='petclinic-web.altidev.net.', type='A'] but it already exists (Service: AmazonRoute53; Status Code: 400; Error Code: InvalidChangeBatch; Request ID: 5b3bad55-f814-11e5-8bb6-5d1c0d70c5a7)
17:16:37,646 INFO  [stdout](pool-15-thread-5)  at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1383) ~[aws-java-sdk-core-1.10.61.jar:?]
17:16:37,646 INFO  [stdout](pool-15-thread-5)  at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902) ~[aws-java-sdk-core-1.10.61.jar:?]
17:16:37,646 INFO  [stdout](pool-15-thread-5)  at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607) ~[aws-java-sdk-core-1.10.61.jar:?]
17:16:37,646 INFO  [stdout](pool-15-thread-5)  at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376) ~[aws-java-sdk-core-1.10.61.jar:?]
17:16:37,646 INFO  [stdout](pool-15-thread-5)  at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338) ~[aws-java-sdk-core-1.10.61.jar:?]
17:16:37,646 INFO  [stdout](pool-15-thread-5)  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287) ~[aws-java-sdk-core-1.10.61.jar:?]
17:16:37,646 INFO  [stdout](pool-15-thread-5)  at com.amazonaws.services.route53.AmazonRoute53Client.invoke(AmazonRoute53Client.java:3689) ~[aws-java-sdk-route53-1.10.61.jar:?]
17:16:37,646 INFO  [stdout](pool-15-thread-5)  at com.amazonaws.services.route53.AmazonRoute53Client.changeResourceRecordSets(AmazonRoute53Client.java:468) ~[aws-java-sdk-route53-1.10.61.jar:?]
17:16:37,647 INFO  [stdout](pool-15-thread-5)  at org.ecloudmanager.service.aws.AWSVmService.createDnsRecord(AWSVmService.java:151) ~[classes:?]
17:16:37,647 INFO  [stdout](pool-15-thread-5)  at org.ecloudmanager.service.aws.AWSVmService.createVm(AWSVmService.java:108) ~[classes:?]
17:16:37,647 INFO  [stdout](pool-15-thread-5)  at org.ecloudmanager.actions.AWSVmActions.lambda$getCreateVmAction$0(AWSVmActions.java:53) ~[classes:?]
17:16:37,647 INFO  [stdout](pool-15-thread-5)  at org.ecloudmanager.actions.AWSVmActions$$Lambda$170/1365767617.run(Unknown Source) ~[?:?]
17:16:37,647 INFO  [stdout](pool-15-thread-5)  at org.ecloudmanager.service.execution.SingleAction.run(SingleAction.java:100) [classes:?]
17:16:37,647 INFO  [stdout](pool-15-thread-5)  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
17:16:37,647 INFO  [stdout](pool-15-thread-5)  at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
17:16:37,647 INFO  [stdout](pool-15-thread-5)  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_31]
17:16:37,647 INFO  [stdout](pool-15-thread-5)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_31]
17:16:37,647 INFO  [stdout](pool-15-thread-5)  at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]

**Comment by ovkhasch** [comment]
Yes, you need to delete this recordset manually to be able to deploy again
