### ISSUE TITLE
HAProxy backends registration should be automatic/hidden to the user

### ISSUE THREAD

**Issue by vshipb** [AltisourceLabs/ecloudmanager#6]
Currently VMs in ComponentGroup should contain cookbook 'rf_infra-etcd_registrator'.
This means we can not use the same VM template for standalone VMs and VMs in ComponentGroup.
Also this cookbook attributes should be configured by the user.

![haproxy](https://cloud.githubusercontent.com/assets/1787811/14245314/371dd38c-fa69-11e5-9171-60759469f08c.PNG)

I think ComponentGroupDeployer should register HAProxy backends in etcd (same way as frontends registration implemented).

**Comment by ovkhasch** [comment]
The main purpose of etcd_registrator was to keep etcd entries haproxy
config in synch. I.e. when backend server goes down - it is removed from
haproxy config. If we move the responsibility of keeping backend server
entries to ComponentGroupDeployer - this functionality will not be
available any more

**Comment by ovkhasch** [comment]
If we want to keep the functionality, mentioned in the previous comment -
we can configure and add to runlist rf_infra-etcd_registrator internally
without any user input.
